author = 'Chloe Ta'

def crazy_lib():
    name1 = input('Enter the name of someone (fictional or real): ')
    country = input('Enter a country: ')
    ful = input('Enter an adjective ending with -ful: ')
    time = input('Enter a time of day: ')
    pasttenseverb = input('Enter an action verb in the past tense: ')
    place1 = input('Enter a name of a location: ')
    prof1 = input('Enter a profession: ')
    name2 = input('Enter the name of someone (fictional or real): ')
    adv1 = input('Enter an adverb ending with -ly: ')
    bone = input('Enter a bone: ')
    show = input('Enter a show (tv show, cartoons, movies...): ')
    verbing1 = input('Enter a verb ending with -ing: ')
    fam_mem = input('Enter a family member (brother,mother, uncle): ')
    pasttenseverb2 = input('Enter an action verb in the past tense: ')
    adv2 = input('Enter an adverb ending with -ly: ')
    pasttenseverb3 = input('Enter an action verb in the past tense: ')
    adj = input('Enter an adjective: ')
    name3 = input('Enter a name of someone (fictional or real): ')
    pasttenseverb4 = input('Enter an action verb in the past tense: ')
    
    print(name1,'had always wanted to go to', country,'.')
    print('However, on one', ful, time, 'they', pasttenseverb,'down the', place1,'.')
    print(name1,'had to visit the', prof1,',', name2)
    print('They should know what to do.')
    print(adv1, name1,'had broken their',bone,', and could not go to',place1,'.')
    print('Instead, they watched', show,'while',verbing1,'for their', fam_mem,'to', pasttenseverb2,'them.')
    print(adv2, name1, pasttenseverb3,'and their', adj,'friend,',name3,',', pasttenseverb4,', very hard.')