author = 'Claire Gao'

#input('Enter a : ')
def crazy_lib():
    print('Welcome to Claire\'s Crazy Lib !!\n')
    month = input('Enter a month: ')
    date = input('Enter a number between 1 and 50: ')
    year = input('Enter a number between 2000 and 50000: ')
    numberth = input('Enter a number between 1 and 200 in the form or counting like 1st, 2nd, 3rd, etc.: ')
    junglename = input('Enter any word (preferably silly): ')
    placename = input('Enter any other word (also silly): ')
    comrade1 = input('Enter a name: ')
    comrade2 = input('Enter a name: ')
    adj1 = input('Enter an adjective: ')
    color = input('Enter a color: ')
    noun1 = input('Enter a noun: ')
    fruit = input('Enter a fruit: ')
    distance = input('Enter a large number: ')
    adj2 = input('Enter an adjective: ')
    verb1 = input('Enter a verb (plural): ')
    nanodays = input('Enter a big number: ')
    direction = input('Enter a direction: ')
    animal = input('Enter an animal: ')
    flying = input('Enter a verb ending in "-ing": ')
    
    print('\n',month,date,',',year,'\n')
    print('Today was the',numberth,'day of our expedition in the',junglename,'jungle in', placename,'.' )
    print('We (I and my comrades,',comrade1,'and',comrade2,') have been getting closer to what we are on this mission for:' )
    print('the',adj1,color,noun1,'known as the',fruit,'in the folktales! Today, we walked',distance,'kilomillimiles')
    print('deeper towards the',adj2,'altar in which the last', fruit,verb1,'.')
    print('By our estimates, we should be able to get there by the next Fivessday in about',nanodays,'nanodays!')
    print('Tomorrow, we will head',direction,'to find the source of the',animal,'noises we have heard',flying,'over us.')