
def crazy_lib():
    noun1 = input("Enter a name of someone you know: ")
    num1 = input("Enter a number: ")
    ask1 = input("Enter a place: ")
    adj1 = input("Enter a feeling (ex:jealous, tired, etc.): ")
    noun2 = input("Enter a sport: ")
    game = input("Enter a board game: ")
    adj2 = input("Enter an adjective: ")
    verb1 = input("Enter a verb ending with -ing (make the first letter uppercase): ")
    num2 = input("Enter a number: ")
    adj3 = input("Enter an adjective: ")
    adv = input("Enter an adverb: ")
    verb2 = input("Enter an action verb ending with -ing: ")
    place = input("Enter a place: ")
    noun3 = input("Enter a plural noun: ")
    time = input("Enter a time of day (ex: 3 am): ")
    act = input("Enter an activity: ")
    verb = input("Enter an action verb: ")
    place = input("Enter a location: ")
    year = input("Enter a year: ")
    adv1 = input("Enter an adverb: ")
    name = input("Enter a made up word with the first letter being capital: ")

    print("Dear",noun1,",")
    print("     We are",adj1,"to inform you that you have been accepted to",ask1,"University.I must say, I was truly impressed by your SAT score of",num1,", and your",adj2,"resume.",verb1,noun2,"and",game,"to start a new international sport shows that you always give a",num2,"percent to anything you work for. Now I can imagine that this is some",adj3,"news. You are",adv,verb2,"in your",place,"right now, telling all your",noun3,"about this news. However, it is currently",time,"right now, and it is time for me to do my daily ritual of",act,", so i must",verb,"this letter up. So anyway, welcome,",noun1,"to this",place,", member of the Class of",year )
    print("                                    ",adv1,",")
    print("                                         Mr.",name)

